version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  labels:
  - automerge
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: nokogiri
    versions:
    - 1.11.3
  - dependency-name: mimemagic
    versions:
    - 0.3.9
  - dependency-name: mini_portile2
    versions:
    - 2.5.0
